### ISSUE TITLE
3-0-stable version

### ISSUE THREAD

**Issue by jdatti** [spree-contrib/spree_reviews#131]
Are you guys planning on 3-0-stable version which points to spree 3-0 branch.

Current spree_reviews master points to 3.1.0.beta and there's no 3-0-stable branch. We're planning on upgrading to spree 3-0-stable branch and we're stuck here.

**Comment by futhr** [comment]
Hi @jdatti, a `3-0-stable` branch now created. Happy coding!

**Comment by jdatti** [comment]
@futhr Thank You. You guys rock.
