### ISSUE TITLE
translation_missing" title="translation missing: en.spree.you_must_enter_value_for_rating

### ISSUE THREAD

**Issue by anand-supernova** [spree-contrib/spree_reviews#152]
Rating <span class="translation_missing" title="translation missing: en.spree.you_must_enter_value_for_rating">You Must Enter Value For Rating</span>

I am constantly getting this issue Even I added "you_must_enter_value_for_rating" in my locale file

Am I doing something wrong?

**Comment by bacancy-namrata** [comment]
I am getting same issue.
can any one help me to resolve this?

**Comment by Leo137** [comment]
https://expertise.jetruby.com/spree-commerce-development-issues-localization-53522acce7c0

**Comment by edmondchui** [comment]
The fix in pull request#187 should fix this issue.
