### ISSUE TITLE
Stars not showing properly

### ISSUE THREAD

**Issue by NuclearMachine** [spree-contrib/spree_reviews#161]
![selection_093](https://user-images.githubusercontent.com/20434532/32775347-236b5c5c-c96a-11e7-8ccf-a4636cf9ab30.jpg)

**Comment by NuclearMachine** [comment]
so i had to manually include it in the application.js then the stars show.

**Comment by akram71093** [comment]
@NuclearMachine  I have the same problem. What did you exactly include in application.js?
