### ISSUE TITLE
Partials missing

### ISSUE THREAD

**Issue by batianusrey** [spree-contrib/spree_reviews#164]
Hey, guys.

I'm using the gem and the `3.3.0` version is installed. However, when I performed the `spree_reviews:install` none of the partials mentioned [here](https://github.com/spree-contrib/spree_reviews#usage) were created. What is the correct approach to override this partials and modify their look and feel.

Do I need to manually created them?

Apologies if this is not the correct way of asking.

Thanks!

**Comment by eficiatech** [comment]
They are in the folder app/views/spree/shared you can find them in the original gem and copy them over to your project to edit them. Rails will recognize the files and use yours instead.
