### ISSUE TITLE
Cannot Install spree_reviews using Spree 4.0

### ISSUE THREAD

**Issue by muengineer** [spree-contrib/spree_reviews#173]
Hello. I am trying to install spree_reviews from a fresh install of Spree Commerce 4.0.  I have attached my gem file.  As per the instructions on your site, I placed,  gem 'spree_reviews', github: 'spree-contrib/spree_reviews', in the gem file and ran the bundle command. When I did, I received the following error:

Bundler could not find compatible versions for gem "spree_auth_devise":
  In snapshot (Gemfile.lock): spree_auth_devise (= 4.0.0)
  
  In Gemfile: spree_auth_devise (~> 4.0)

    spree_reviews was resolved to 3.3.0, which depends on
      spree_auth_devise (>= 3.1.0, < 4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

After which, I ran bundle update and then received the following error:

Bundler could not find compatible versions for gem "spree_auth_devise":
  In Gemfile: spree_auth_devise (~> 4.0)

    spree_reviews was resolved to 3.3.0, which depends on
      spree_auth_devise (>= 3.1.0, < 4.0)

Thank you in advanced for your assistance with this issue.
[gemfile.txt](https://github.com/spree-contrib/spree_reviews/files/3842447/gemfile.txt)

**Comment by aamir-tauqeer** [comment]
This clearly shows that spree_reviews are not compatible with spree_auth_devise version you have, which implies it is not compatible with spree 4.

**Comment by muengineer** [comment]
I think I was trying to let them know that this was an issue with a fresh install and that I was following their instructions and I was getting error.  Regardless, I will close it out.
