### ISSUE TITLE
Incompatible with Spree 4.1

### ISSUE THREAD

**Issue by cl0udmaker** [spree-contrib/spree_reviews#177]
Extension depends on spree_auth_devise  (>= 3.1.0, < 4.0) and newest version is spree_auth_devise (= 4.1.0)
Any plans to issue an update?

**Comment by runlevel5** [comment]
@cl0udmaker feel free to submit PR

**Comment by ronzalo** [comment]
there already two PR to support latest Spree, but this extension seems inactive

**Comment by sunil123456** [comment]
Hello is there anyone got solution how to resolve incompatible issue for spree_reviews?:

Bundler could not find compatible versions for gem "spree_auth_devise":
  In Gemfile:
    spree_auth_devise (~> 4.1)

    spree_reviews was resolved to 3.3.0, which depends on
      spree_auth_devise (>= 3.1.0, < 4.0)

**Comment by poudelprakash** [comment]
https://github.com/spree-contrib/spree_reviews/pull/179
You can use https://github.com/TruemarkDev/spree_reviews for now for spree 4.1+ compatibility

**Comment by damianlegawiec** [comment]
This is now fixed
