### ISSUE TITLE
Radio buttons instead of stars?

### ISSUE THREAD

**Issue by Allanon29** [spree-contrib/spree_reviews#99]
Hi Guys,

I've just tried the 2.2 branch and instead of stars, like in 2.1, only radio buttons appear. Is this a bug, or this is by design? (I liked stars better).

If this is by design, then I think stars should still be an option in the Review settings menu. Like "Display stars instead of radio buttons".

Best Wishes,
Matt

**Comment by Hasan243** [comment]
same issue occuring on sree 3-0-stable 
already tried updating bundle but still i am getting checkboxes
